import type { Company } from "./schemas.js";

export const COMPANIES: readonly Company[] = Object.freeze([
  {
    id: "company:figma",
    slug: "figma",
    name: "Figma",
    websiteUrl: "https://www.figma.com/",
    careersUrl: "https://www.figma.com/careers/",
    industry: "design-software",
    status: "active",
  },
  {
    id: "company:rubrik",
    slug: "rubrik",
    name: "Rubrik",
    websiteUrl: "https://www.rubrik.com/",
    careersUrl: "https://www.rubrik.com/company/careers",
    industry: "cybersecurity",
    status: "active",
  },
  {
    id: "company:mistral-ai",
    slug: "mistral-ai",
    name: "Mistral AI",
    websiteUrl: "https://mistral.ai/",
    careersUrl: "https://mistral.ai/careers",
    industry: "artificial-intelligence",
    status: "active",
  },
  {
    id: "company:mindtickle",
    slug: "mindtickle",
    name: "Mindtickle",
    websiteUrl: "https://www.mindtickle.com/",
    careersUrl: "https://www.mindtickle.com/careers/",
    industry: "sales-enablement",
    status: "active",
  },
  {
    id: "company:replit",
    slug: "replit",
    name: "Replit",
    websiteUrl: "https://replit.com/",
    careersUrl: "https://replit.com/careers",
    industry: "developer-tools",
    status: "active",
  },
  {
    id: "company:vanta",
    slug: "vanta",
    name: "Vanta",
    websiteUrl: "https://www.vanta.com/",
    careersUrl: "https://www.vanta.com/careers",
    industry: "cybersecurity",
    status: "active",
  },
  {
    id: "company:bosch",
    slug: "bosch",
    name: "Bosch",
    websiteUrl: "https://www.bosch.com/",
    careersUrl: "https://www.bosch.com/careers/",
    industry: "industrial-technology",
    status: "active",
  },
  {
    id: "company:mastercard",
    slug: "mastercard",
    name: "Mastercard",
    websiteUrl: "https://www.mastercard.com/",
    careersUrl: "https://careers.mastercard.com/us/en",
    industry: "financial-services",
    status: "active",
  },
  {
    id: "company:nvidia",
    slug: "nvidia",
    name: "NVIDIA",
    websiteUrl: "https://www.nvidia.com/",
    careersUrl: "https://www.nvidia.com/en-us/about-nvidia/careers/",
    industry: "semiconductors",
    status: "active",
  },
  {
    id: "company:icims",
    slug: "icims",
    name: "iCIMS",
    websiteUrl: "https://www.icims.com/",
    careersUrl: "https://careers.icims.com/",
    industry: "hr-technology",
    status: "active",
  },
  {
    id: "company:sap",
    slug: "sap",
    name: "SAP",
    websiteUrl: "https://www.sap.com/",
    careersUrl: "https://jobs.sap.com/",
    industry: "enterprise-software",
    status: "active",
  },
  {
    id: "company:cognizant",
    slug: "cognizant",
    name: "Cognizant",
    websiteUrl: "https://www.cognizant.com/",
    careersUrl: "https://careers.cognizant.com/",
    industry: "professional-services",
    status: "active",
  },
]);
