import type { JobSource } from "./schemas.js";

const VERIFIED_AT = "2026-07-03";

export const JOB_SOURCES: readonly JobSource[] = Object.freeze([
  {
    id: "source:figma:greenhouse",
    companyId: "company:figma",
    displayName: "Figma Greenhouse board",
    provider: "greenhouse",
    listingUrl: "https://boards.greenhouse.io/figma",
    defaultLocale: "en-US",
    coverage: { mode: "global" },
    status: "active",
    crawlEnabled: false,
    priority: 70,
    verification: { status: "verified", lastCheckedAt: VERIFIED_AT },
    config: { boardToken: "figma" },
  },
  {
    id: "source:rubrik:greenhouse",
    companyId: "company:rubrik",
    displayName: "Rubrik Greenhouse board",
    provider: "greenhouse",
    listingUrl: "https://boards.greenhouse.io/rubrik",
    defaultLocale: "en-US",
    coverage: { mode: "global" },
    status: "active",
    crawlEnabled: false,
    priority: 70,
    verification: { status: "verified", lastCheckedAt: VERIFIED_AT },
    config: { boardToken: "rubrik" },
  },
  {
    id: "source:mistral-ai:lever",
    companyId: "company:mistral-ai",
    displayName: "Mistral AI Lever board",
    provider: "lever",
    listingUrl: "https://jobs.lever.co/mistral",
    defaultLocale: "en-US",
    coverage: { mode: "global" },
    status: "active",
    crawlEnabled: false,
    priority: 80,
    verification: { status: "verified", lastCheckedAt: VERIFIED_AT },
    config: { siteSlug: "mistral" },
  },
  {
    id: "source:mindtickle:lever",
    companyId: "company:mindtickle",
    displayName: "Mindtickle Lever board",
    provider: "lever",
    listingUrl: "https://jobs.lever.co/mindtickle",
    defaultLocale: "en-US",
    coverage: { mode: "global" },
    status: "active",
    crawlEnabled: false,
    priority: 85,
    verification: { status: "verified", lastCheckedAt: VERIFIED_AT },
    config: { siteSlug: "mindtickle" },
  },
  {
    id: "source:replit:ashby",
    companyId: "company:replit",
    displayName: "Replit Ashby board",
    provider: "ashby",
    listingUrl: "https://jobs.ashbyhq.com/replit",
    defaultLocale: "en-US",
    coverage: { mode: "global" },
    status: "active",
    crawlEnabled: false,
    priority: 80,
    verification: { status: "verified", lastCheckedAt: VERIFIED_AT },
    config: { organizationSlug: "replit" },
  },
  {
    id: "source:vanta:ashby",
    companyId: "company:vanta",
    displayName: "Vanta Ashby board",
    provider: "ashby",
    listingUrl: "https://jobs.ashbyhq.com/vanta",
    defaultLocale: "en-US",
    coverage: { mode: "global" },
    status: "active",
    crawlEnabled: false,
    priority: 75,
    verification: { status: "verified", lastCheckedAt: VERIFIED_AT },
    config: { organizationSlug: "vanta" },
  },
  {
    id: "source:bosch:smartrecruiters",
    companyId: "company:bosch",
    displayName: "Bosch SmartRecruiters board",
    provider: "smartrecruiters",
    listingUrl: "https://jobs.smartrecruiters.com/?company=BoschGroup",
    defaultLocale: "en-US",
    coverage: { mode: "global" },
    status: "active",
    crawlEnabled: false,
    priority: 70,
    verification: { status: "verified", lastCheckedAt: VERIFIED_AT },
    config: { companyIdentifier: "BoschGroup" },
  },
  {
    id: "source:mastercard:workday",
    companyId: "company:mastercard",
    displayName: "Mastercard Workday board",
    provider: "workday",
    listingUrl: "https://mastercard.wd1.myworkdayjobs.com/CorporateCareers",
    defaultLocale: "en-US",
    coverage: { mode: "global" },
    status: "active",
    crawlEnabled: false,
    priority: 90,
    verification: { status: "verified", lastCheckedAt: VERIFIED_AT },
    config: {
      host: "mastercard.wd1.myworkdayjobs.com",
      tenant: "mastercard",
      site: "CorporateCareers",
    },
  },
  {
    id: "source:nvidia:workday",
    companyId: "company:nvidia",
    displayName: "NVIDIA Workday board",
    provider: "workday",
    listingUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite",
    defaultLocale: "en-US",
    coverage: { mode: "global" },
    status: "active",
    crawlEnabled: false,
    priority: 90,
    verification: { status: "verified", lastCheckedAt: VERIFIED_AT },
    config: {
      host: "nvidia.wd5.myworkdayjobs.com",
      tenant: "nvidia",
      site: "NVIDIAExternalCareerSite",
    },
  },
  {
    id: "source:icims:icims",
    companyId: "company:icims",
    displayName: "iCIMS careers board",
    provider: "icims",
    listingUrl: "https://careers.icims.com/careers-home/jobs",
    defaultLocale: "en-US",
    coverage: { mode: "global" },
    status: "active",
    crawlEnabled: false,
    priority: 60,
    verification: { status: "verified", lastCheckedAt: VERIFIED_AT },
    config: {
      host: "careers.icims.com",
      sitePath: "careers-home",
    },
  },
  {
    id: "source:sap:successfactors",
    companyId: "company:sap",
    displayName: "SAP SuccessFactors careers board",
    provider: "successfactors",
    listingUrl: "https://jobs.sap.com/",
    defaultLocale: "en-US",
    coverage: { mode: "global" },
    status: "active",
    crawlEnabled: false,
    priority: 85,
    verification: { status: "verified", lastCheckedAt: VERIFIED_AT },
    config: {
      host: "jobs.sap.com",
      sitePath: "/",
      companyIdentifier: "sap",
    },
  },
  {
    id: "source:cognizant:taleo",
    companyId: "company:cognizant",
    displayName: "Cognizant Taleo careers board",
    provider: "taleo",
    listingUrl: "https://cognizant.taleo.net/careersection/lateral/default.ftl",
    defaultLocale: "en-US",
    coverage: { mode: "global" },
    status: "active",
    crawlEnabled: false,
    priority: 85,
    verification: { status: "verified", lastCheckedAt: VERIFIED_AT },
    config: {
      host: "cognizant.taleo.net",
      careerSection: "lateral",
      pageName: "default.ftl",
      locale: "en-US",
    },
  },
]);
