import type { Skill, SkillCategory, SkillKind } from "./schemas.js";

const defineSkillCategories = (
  entries: readonly (readonly [slug: string, label: string, description: string])[],
): readonly SkillCategory[] =>
  Object.freeze(
    entries.map(([slug, label, description]) => ({
      id: `skill-category:${slug}`,
      slug,
      label,
      description,
      status: "active" as const,
    })),
  );

const defineSkills = (
  categorySlug: string,
  kind: SkillKind,
  entries: readonly (readonly [slug: string, label: string])[],
): readonly Skill[] =>
  Object.freeze(
    entries.map(([slug, label]) => ({
      id: `skill:${slug}`,
      slug,
      label,
      categoryId: `skill-category:${categorySlug}`,
      kind,
      status: "active" as const,
    })),
  );

export const SKILL_CATEGORIES = defineSkillCategories(
  [
    ["programming-languages", "Programming Languages", "General-purpose, systems, scripting, query, and shell languages."],
    ["web-frontend", "Web Frontend", "Browser technologies, frontend frameworks, state management, and build tooling."],
    ["backend-api", "Backend and APIs", "Server frameworks, API technologies, and backend application platforms."],
    ["mobile", "Mobile Development", "Native and cross-platform mobile application technologies."],
    ["data-engineering", "Data Engineering", "Batch, streaming, orchestration, warehouse, and transformation technologies."],
    ["data-analytics", "Data Analytics and BI", "Business intelligence, numerical analysis, visualization, and notebook tooling."],
    ["ai-ml", "AI and Machine Learning", "Machine learning frameworks, model platforms, and applied AI concepts."],
    ["databases-search", "Databases and Search", "Relational, document, key-value, graph, search, and analytical data stores."],
    ["cloud", "Cloud Platforms", "Public cloud providers and major managed compute, storage, and container services."],
    ["devops-platform", "DevOps and Platform Engineering", "Infrastructure as code, automation, CI/CD, and platform delivery tooling."],
    ["containers-orchestration", "Containers and Orchestration", "Container runtimes and container orchestration platforms."],
    ["messaging-streaming", "Messaging and Streaming", "Queues, publish-subscribe systems, event streaming, and managed messaging."],
    ["testing-quality", "Testing and Quality", "Testing frameworks, test tooling, quality platforms, and testing practices."],
    ["security-identity", "Security and Identity", "Security standards, identity systems, security tools, and security practices."],
    ["observability", "Observability", "Metrics, logs, traces, telemetry, dashboards, and application monitoring."],
    ["architecture", "Architecture and Engineering Practices", "Software architecture styles, system design, and engineering practices."],
    ["operating-systems", "Operating Systems", "Desktop, server, and Unix-family operating systems."],
    ["version-control", "Version Control and Source Hosting", "Distributed version control and source-code collaboration platforms."],
    ["delivery-collaboration", "Delivery and Collaboration", "Delivery methods, agile practices, planning, and documentation tools."],
    ["enterprise-platforms", "Enterprise Platforms", "CRM, ERP, workflow, BPM, and enterprise service-management platforms."],
    ["domain-knowledge", "Domain Knowledge", "Industry and business-domain knowledge frequently requested in job descriptions."],
  ] as const,
);

export const SKILLS: readonly Skill[] = Object.freeze([
  ...defineSkills(
    "programming-languages",
    "language",
    [
      ["javascript", "JavaScript"],
      ["typescript", "TypeScript"],
      ["python", "Python"],
      ["java", "Java"],
      ["c-sharp", "C#"],
      ["c", "C"],
      ["cpp", "C++"],
      ["go", "Go"],
      ["rust", "Rust"],
      ["kotlin", "Kotlin"],
      ["swift", "Swift"],
      ["php", "PHP"],
      ["ruby", "Ruby"],
      ["scala", "Scala"],
      ["r", "R"],
      ["sql", "SQL"],
      ["bash", "Bash"],
      ["powershell", "PowerShell"],
    ] as const,
  ),
  ...defineSkills(
    "web-frontend",
    "framework",
    [
      ["react", "React"],
      ["nextjs", "Next.js"],
      ["angular", "Angular"],
      ["vuejs", "Vue.js"],
      ["svelte", "Svelte"],
      ["html", "HTML"],
      ["css", "CSS"],
      ["tailwind-css", "Tailwind CSS"],
      ["redux", "Redux"],
      ["webpack", "Webpack"],
      ["vite", "Vite"],
    ] as const,
  ),
  ...defineSkills(
    "backend-api",
    "framework",
    [
      ["nodejs", "Node.js"],
      ["expressjs", "Express.js"],
      ["fastify", "Fastify"],
      ["nestjs", "NestJS"],
      ["spring-boot", "Spring Boot"],
      ["aspnet-core", "ASP.NET Core"],
      ["django", "Django"],
      ["flask", "Flask"],
      ["fastapi", "FastAPI"],
      ["ruby-on-rails", "Ruby on Rails"],
      ["laravel", "Laravel"],
      ["graphql", "GraphQL"],
      ["rest-api", "REST API"],
      ["grpc", "gRPC"],
    ] as const,
  ),
  ...defineSkills(
    "mobile",
    "framework",
    [
      ["android", "Android"],
      ["ios", "iOS"],
      ["react-native", "React Native"],
      ["flutter", "Flutter"],
    ] as const,
  ),
  ...defineSkills(
    "data-engineering",
    "platform",
    [
      ["apache-spark", "Apache Spark"],
      ["apache-hadoop", "Apache Hadoop"],
      ["apache-airflow", "Apache Airflow"],
      ["dbt", "dbt"],
      ["apache-flink", "Apache Flink"],
      ["apache-beam", "Apache Beam"],
      ["databricks", "Databricks"],
      ["snowflake", "Snowflake"],
      ["bigquery", "BigQuery"],
      ["redshift", "Amazon Redshift"],
      ["azure-data-factory", "Azure Data Factory"],
    ] as const,
  ),
  ...defineSkills(
    "data-analytics",
    "tool",
    [
      ["power-bi", "Power BI"],
      ["tableau", "Tableau"],
      ["looker", "Looker"],
      ["microsoft-excel", "Microsoft Excel"],
      ["pandas", "pandas"],
      ["numpy", "NumPy"],
      ["jupyter", "Jupyter"],
      ["matplotlib", "Matplotlib"],
    ] as const,
  ),
  ...defineSkills(
    "ai-ml",
    "framework",
    [
      ["pytorch", "PyTorch"],
      ["tensorflow", "TensorFlow"],
      ["scikit-learn", "scikit-learn"],
      ["xgboost", "XGBoost"],
      ["lightgbm", "LightGBM"],
      ["hugging-face", "Hugging Face"],
      ["langchain", "LangChain"],
      ["llamaindex", "LlamaIndex"],
      ["ollama", "Ollama"],
      ["mlflow", "MLflow"],
      ["kubeflow", "Kubeflow"],
    ] as const,
  ),
  ...defineSkills(
    "ai-ml",
    "concept",
    [
      ["machine-learning", "Machine Learning"],
      ["deep-learning", "Deep Learning"],
      ["natural-language-processing", "Natural Language Processing"],
      ["computer-vision", "Computer Vision"],
      ["generative-ai", "Generative AI"],
      ["large-language-models", "Large Language Models"],
      ["retrieval-augmented-generation", "Retrieval-Augmented Generation"],
      ["prompt-engineering", "Prompt Engineering"],
      ["feature-engineering", "Feature Engineering"],
      ["model-serving", "Model Serving"],
    ] as const,
  ),
  ...defineSkills(
    "databases-search",
    "database",
    [
      ["postgresql", "PostgreSQL"],
      ["mysql", "MySQL"],
      ["microsoft-sql-server", "Microsoft SQL Server"],
      ["oracle-database", "Oracle Database"],
      ["mongodb", "MongoDB"],
      ["redis", "Redis"],
      ["elasticsearch", "Elasticsearch"],
      ["dynamodb", "Amazon DynamoDB"],
      ["cassandra", "Apache Cassandra"],
      ["neo4j", "Neo4j"],
      ["sqlite", "SQLite"],
    ] as const,
  ),
  ...defineSkills(
    "cloud",
    "platform",
    [
      ["aws", "Amazon Web Services"],
      ["microsoft-azure", "Microsoft Azure"],
      ["google-cloud", "Google Cloud"],
      ["aws-ec2", "Amazon EC2"],
      ["aws-lambda", "AWS Lambda"],
      ["aws-s3", "Amazon S3"],
      ["aws-eks", "Amazon EKS"],
      ["aws-ecs", "Amazon ECS"],
      ["azure-functions", "Azure Functions"],
      ["azure-aks", "Azure Kubernetes Service"],
      ["google-gke", "Google Kubernetes Engine"],
      ["google-cloud-run", "Google Cloud Run"],
    ] as const,
  ),
  ...defineSkills(
    "devops-platform",
    "tool",
    [
      ["terraform", "Terraform"],
      ["pulumi", "Pulumi"],
      ["ansible", "Ansible"],
      ["jenkins", "Jenkins"],
      ["github-actions", "GitHub Actions"],
      ["gitlab-ci", "GitLab CI/CD"],
      ["azure-devops", "Azure DevOps"],
      ["argo-cd", "Argo CD"],
      ["helm", "Helm"],
      ["nix", "Nix"],
    ] as const,
  ),
  ...defineSkills(
    "containers-orchestration",
    "platform",
    [
      ["docker", "Docker"],
      ["kubernetes", "Kubernetes"],
      ["openshift", "Red Hat OpenShift"],
      ["containerd", "containerd"],
    ] as const,
  ),
  ...defineSkills(
    "messaging-streaming",
    "platform",
    [
      ["apache-kafka", "Apache Kafka"],
      ["rabbitmq", "RabbitMQ"],
      ["aws-sqs", "Amazon SQS"],
      ["aws-sns", "Amazon SNS"],
      ["amazon-kinesis", "Amazon Kinesis"],
      ["google-pubsub", "Google Cloud Pub/Sub"],
    ] as const,
  ),
  ...defineSkills(
    "testing-quality",
    "tool",
    [
      ["jest", "Jest"],
      ["vitest", "Vitest"],
      ["playwright", "Playwright"],
      ["cypress", "Cypress"],
      ["selenium", "Selenium"],
      ["junit", "JUnit"],
      ["pytest", "pytest"],
      ["cucumber", "Cucumber"],
      ["postman", "Postman"],
      ["pact", "Pact"],
      ["sonarqube", "SonarQube"],
    ] as const,
  ),
  ...defineSkills(
    "testing-quality",
    "concept",
    [
      ["unit-testing", "Unit Testing"],
      ["integration-testing", "Integration Testing"],
      ["end-to-end-testing", "End-to-End Testing"],
      ["performance-testing", "Performance Testing"],
      ["test-automation", "Test Automation"],
    ] as const,
  ),
  ...defineSkills(
    "security-identity",
    "standard",
    [
      ["oauth2", "OAuth 2.0"],
      ["openid-connect", "OpenID Connect"],
      ["saml", "SAML"],
      ["jwt", "JSON Web Token"],
    ] as const,
  ),
  ...defineSkills(
    "security-identity",
    "tool",
    [
      ["hashicorp-vault", "HashiCorp Vault"],
      ["spiffe-spire", "SPIFFE/SPIRE"],
      ["owasp-zap", "OWASP ZAP"],
      ["veracode", "Veracode"],
    ] as const,
  ),
  ...defineSkills(
    "security-identity",
    "concept",
    [
      ["owasp", "OWASP"],
      ["identity-access-management", "Identity and Access Management"],
      ["zero-trust", "Zero Trust"],
      ["sast", "Static Application Security Testing"],
      ["dast", "Dynamic Application Security Testing"],
      ["threat-modeling", "Threat Modeling"],
    ] as const,
  ),
  ...defineSkills(
    "observability",
    "tool",
    [
      ["prometheus", "Prometheus"],
      ["grafana", "Grafana"],
      ["opentelemetry", "OpenTelemetry"],
      ["datadog", "Datadog"],
      ["splunk", "Splunk"],
      ["elastic-stack", "Elastic Stack"],
      ["new-relic", "New Relic"],
    ] as const,
  ),
  ...defineSkills(
    "architecture",
    "concept",
    [
      ["microservices", "Microservices"],
      ["event-driven-architecture", "Event-Driven Architecture"],
      ["distributed-systems", "Distributed Systems"],
      ["system-design", "System Design"],
      ["domain-driven-design", "Domain-Driven Design"],
      ["cqrs", "CQRS"],
      ["api-design", "API Design"],
      ["design-patterns", "Design Patterns"],
      ["clean-architecture", "Clean Architecture"],
    ] as const,
  ),
  ...defineSkills(
    "operating-systems",
    "platform",
    [
      ["linux", "Linux"],
      ["windows", "Windows"],
      ["unix", "Unix"],
      ["macos", "macOS"],
    ] as const,
  ),
  ...defineSkills(
    "version-control",
    "tool",
    [
      ["git", "Git"],
      ["github", "GitHub"],
      ["gitlab", "GitLab"],
      ["bitbucket", "Bitbucket"],
    ] as const,
  ),
  ...defineSkills(
    "delivery-collaboration",
    "methodology",
    [
      ["agile", "Agile"],
      ["scrum", "Scrum"],
      ["kanban", "Kanban"],
      ["devops", "DevOps"],
    ] as const,
  ),
  ...defineSkills(
    "delivery-collaboration",
    "tool",
    [
      ["jira", "Jira"],
      ["confluence", "Confluence"],
    ] as const,
  ),
  ...defineSkills(
    "enterprise-platforms",
    "platform",
    [
      ["salesforce", "Salesforce"],
      ["sap", "SAP"],
      ["pega", "Pega"],
      ["camunda", "Camunda"],
      ["servicenow", "ServiceNow"],
    ] as const,
  ),
  ...defineSkills(
    "domain-knowledge",
    "domain",
    [
      ["banking", "Banking"],
      ["payments", "Payments"],
      ["fincrime", "Financial Crime"],
      ["aml", "Anti-Money Laundering"],
      ["kyc", "Know Your Customer"],
      ["ecommerce", "E-commerce"],
      ["healthcare", "Healthcare"],
      ["telecommunications", "Telecommunications"],
    ] as const,
  ),
]);

export const SKILL_CATEGORY_BY_ID: ReadonlyMap<string, SkillCategory> = new Map(
  SKILL_CATEGORIES.map((category) => [category.id, category] as const),
);

export const SKILL_BY_ID: ReadonlyMap<string, Skill> = new Map(
  SKILLS.map((skill) => [skill.id, skill] as const),
);

export const getSkillsForCategory = (categoryId: string): readonly Skill[] =>
  SKILLS.filter((skill) => skill.categoryId === categoryId);
